title: "Gokul Krishna"
author: "Gokul Krishna"
description: "Security Engineer at Lucid Motors. Computer Security researcher focused on vulnerability analysis, fuzzing, and dynamic patching."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation: []                     # accepts {file, title, url, icon, sidebaricon}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:gkgokulkrishna33@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/g0kkk"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

footer:
  - {title: LinkedIn, url: "https://www.linkedin.com/in/gokulkrishna-p-menon-53369bb9"}
  - {title: Google Scholar, url: "https://scholar.google.com/citations?hl=en&user=kYIE-IsAAAAJ"}

plugins:
 - jekyll-feed
